apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  Name: tp-hpo-sherpa
  namespace: orakel
spec:
  serviceAccountName: workflow-pods-lite
  imagePullSecrets:
  - name: gitlab-argo-image-pull-secret
  entrypoint: hpo-sherpa
  volumes:
  - name: s3-config-vol # for 'local' execution
    secret:
      secretName: s3-config-secret
  arguments:
    parameters:
      - name: run_name
        value: "run_lr_nodes"
      - name: input_path
        value: "s3://borakelcrr/lumileds/hpo"
      - name: output_path
        value: "s3://borakelcrr/lumileds/hpo"
      - name: default_parameter
        value: "flagfile.txt"
      - name: hpo_parameter
        value: '{"lr" : {"type":"Continuous","range":[1e-7,1e-1]},"units_1": {"type": "Discrete", "range": [8,128]},"units_2": {"type": "Discrete", "range": [8,16]}}'
      - name: algorithm
        value: "GPyOpt"
      - name: algo_parameter
        value: '{"max_num_trials":5}'
      - name: objective
        value: "mean_squared_error"
      - name: filename_objective
        value: "lr_nodes_metrics.json"
      - name: lower_is_better
        value: "True"
      - name: workflowtemplate
        value: "dag-orakel-lumileds-hpo"
      - name: entrypoint
        value: "orakel-lumileds-hpo"
      - name: max_concurrent
        value: "2"
      - name: resubmit_failed_trials
        value: "False"
      - name: verbose
        value: "True"
      - name: storage_strategy
        value: 'best'
      - name: argo_ip
        value: "134.130.7.172"
      - name: argo_port
        value: "32529"
      - name: k8_namespace
        value: "orakel"
  templates:
    - name: hpo-sherpa
      metadata:
        labels:
          app: sherpa-runner-dashboard
          run: "{{workflow.parameters.run_name}}"
      inputs:
        parameters:
        - name: run_name
        - name: input_path
        - name: output_path
        - name: default_parameter
        - name: hpo_parameter
        - name: algorithm
        - name: algo_parameter
        - name: objective
        - name: filename_objective
        - name: lower_is_better
        - name: workflowtemplate
        - name: entrypoint
        - name: max_concurrent
        - name: resubmit_failed_trials
        - name: verbose
        - name: storage_strategy
        - name: argo_ip
        - name: argo_port
        - name: k8_namespace
      container:
        env:
        - name: api_exec_token
          valueFrom:
            secretKeyRef:
              name: argo-api-exec-token
              key: api-exec-token
        volumeMounts:
        - name: s3-config-vol
          mountPath: "/code/s3config"
        name: main
        image: registry.git-ce.rwth-aachen.de/wzl-mq-ms-rpc/code/research/predictive-quality/ml-pipline-blocks/hpo-sherpa:embedded
        imagePullPolicy: Always
        args:
        - --run_name={{inputs.parameters.run_name}}
        - --input_path={{inputs.parameters.input_path}}
        - --output_path={{inputs.parameters.output_path}}
        - --default_parameter={{inputs.parameters.default_parameter}}
        - --hpo_parameter={{inputs.parameters.hpo_parameter}}
        - --algorithm={{inputs.parameters.algorithm}}
        - --algo_parameter={{inputs.parameters.algo_parameter}}
        - --objective={{inputs.parameters.objective}}
        - --filename_objective={{inputs.parameters.filename_objective}}
        - --lower_is_better={{inputs.parameters.lower_is_better}}
        - --workflowtemplate={{inputs.parameters.workflowtemplate}}
        - --entrypoint={{inputs.parameters.entrypoint}}
        - --max_concurrent={{inputs.parameters.max_concurrent}}
        - --resubmit_failed_trials={{inputs.parameters.resubmit_failed_trials}}
        - --verbose={{inputs.parameters.verbose}}
        - --storage_strategy={{inputs.parameters.storage_strategy}}
        - --argo_ip={{inputs.parameters.argo_ip}}
        - --argo_port={{inputs.parameters.argo_port}}
        - --k8_namespace={{inputs.parameters.k8_namespace}}
